package laporan;//GEN-LINE:variables
import fungsi.koneksiDB;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgRL4A extends javax.swing.JDialog {
    private final validasi Valid=new validasi();
    private final Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2,ps3;
    private ResultSet rs,rs2;
    private StringBuilder htmlContent;
    // Variabel Baru Sesuai Kebutuhan (Sama seperti DlgRL4ASebab)
    private int hr1s7l=0, hr1s7p=0, hr8s28l=0, hr8s28p=0,
                hr29k3blnl=0, hr29k3blnp=0, // 29 hari sd < 3 bulan
                bln3s5l=0, bln3s5p=0,     // 3 bulan sd < 6 bulan (atau 3-5 bulan)
                bln6s11l=0, bln6s11p=0,   // 6 bulan sd 11 bulan
                th1s4l=0, th1s4p=0,       // 1 th sd 4 th
                th5s9l=0, th5s9p=0,       // 5 th sd 9 th
                th10s14l=0, th10s14p=0,   // 10 th sd 14 th
                th15s19l=0, th15s19p=0,   // 15 th sd 19 th
                th20s24l=0, th20s24p=0,   // 20 th sd 24 th
                th25s29l=0, th25s29p=0,   // 25 th sd 29 th
                th30s34l=0, th30s34p=0,   // 30 th sd 34 th
                th35s39l=0, th35s39p=0,   // 35 th sd 39 th
                th40s44l=0, th40s44p=0,   // 40 th sd 44 th
                th45s49l=0, th45s49p=0,   // 45 th sd 49 th
                th50s54l=0, th50s54p=0,   // 50 th sd 54 th
                th55s59l=0, th55s59p=0,   // 55 th sd 59 th
                th60s64l=0, th60s64p=0,   // 60 th sd 64 th
                th65s69l=0, th65s69p=0,   // 65 th sd 69 th
                th70s74l=0, th70s74p=0,   // 70 th sd 74 th
                th75s79l=0, th75s79p=0,   // 75 th sd 79 th
                th80s84l=0, th80s84p=0,   // 80 th sd 84 th
                lbth85l=0, lbth85p=0,     // >= 85 th
//                matil=0, matip=0, // matil = mati laki-laki, matip = mati perempuan
                mati=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgRL4A(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML1.setEditable(true);
        LoadHTML1.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML1.setDocument(doc);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    private int i=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        TabRawat = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 4A Data Keadaan Morbiditas Pasien Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        TabRawat.setBackground(new java.awt.Color(255, 255, 253));
        TabRawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRawatMouseClicked(evt);
            }
        });

        Scroll.setBorder(null);
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        TabRawat.addTab("Berdasar Tanggal Masuk", Scroll);

        Scroll1.setBorder(null);
        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        TabRawat.addTab("Berdasar Tanggal Keluar", Scroll1);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {                               
    Valid.pindah(evt,BtnCari,Nm);
}                              
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("rl4a.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            if(TabRawat.getSelectedIndex()==0){
                bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }else if(TabRawat.getSelectedIndex()==1){
                bw.write(LoadHTML1.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }                
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }                                        

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {                                    
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }                                   

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {                                     
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }                                    

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
}                                       

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {                                   
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}                                  

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        prosesCari();
    }                                 

    private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
    }                                     

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRL4A dialog = new DlgRL4A(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.editorpane LoadHTML1;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private javax.swing.JTabbedPane TabRawat;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration                   

    // ==================================================================================================================
    // == METODE prosesCari() DIMODIFIKASI ==
    // ==================================================================================================================
    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            // Membuat Header Tabel HTML Baru (Sama seperti DlgRL4ASebab yang dimodifikasi)
             htmlContent.append(
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='3'>No.Urut</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='4%' rowspan='3'>No.Daftar Terperinci</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='15%' rowspan='3'>Golongan Sebab Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='46'>Jumlah Pasien Hidup dan Mati menurut Golongan Umur & Jenis Kelamin</td>"+ // 23 kelompok * 2 gender = 46 kolom
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='6%' colspan='2'>Pasien Keluar (Hidup & Mati) Menurut Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='3%' rowspan='3'>Jumlah Pasien Keluar Hidup (Î£ Kolom L + Î£ Kolom P)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='3%' rowspan='3'>Jumlah Pasien Keluar Mati</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    // Rentang usia baru (tanpa jam)
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-7 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>8-28 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>29hr-<3 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>3-5 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>6-11 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-4 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>5-9 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>10-14 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>15-19 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>20-24 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>25-29 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>30-34 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>35-39 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>40-44 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>45-49 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>50-54 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>55-59 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>60-64 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>65-69 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>70-74 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>75-79 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>80-84 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>â‰¥ 85 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>LK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>PR</td>"+
                "</tr>"+
                 "<tr class='isi'>");
            // Loop untuk L/P di setiap kolom umur
            for(int k=0; k<23; k++){ // 23 kelompok umur baru (tanpa jam)
                htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td><td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>");
            }
            htmlContent.append("</tr>");

            // Baris nomor kolom (Sama seperti DlgRL4ASebab yang dimodifikasi)
            htmlContent.append("<tr class='isi'>");
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"); // No Urut
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"); // No Daftar
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"); // Golongan Sebab
            int colNum = 4;
            for(int k=0; k< (23 * 2); k++){ // Kolom 4 sampai 49 untuk L/P
                 htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>");
            }
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Total LK (Kolom 50)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Total PR (Kolom 51)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Jumlah Hidup (Kolom 52)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum).append("</td>");   // Jumlah Mati (Kolom 53)
            htmlContent.append("</tr>");

            // Query Utama (Dipertahankan dari DlgRL4A.java ASLI - Mengexclude V,W,X,Y)
            // Perhatikan klausa WHERE yang berbeda dari DlgRL4ASebab
            // Koreksi: Logika OR pada query asli salah, seharusnya AND jika ingin exclude SEMUA V,W,X,Y
            // Jika ingin exclude salah satu saja, OR benar. Asumsi: Ingin exclude SEMUA.
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "where diagnosa_pasien.status='Ranap' and reg_periksa.tgl_registrasi between ? and ? and "+
                    " left(diagnosa_pasien.kd_penyakit,1)<>'V' and left(diagnosa_pasien.kd_penyakit,1)<>'W' and "+ // Menggunakan AND
                    " left(diagnosa_pasien.kd_penyakit,1)<>'X' and left(diagnosa_pasien.kd_penyakit,1)<>'Y' "+
                    " group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1; // Reset nomor urut
                while(rs.next()){
                    // Reset semua counter baru (Sama seperti DlgRL4ASebab)
                    hr1s7l=0; hr1s7p=0; hr8s28l=0; hr8s28p=0; hr29k3blnl=0; hr29k3blnp=0;
                    bln3s5l=0; bln3s5p=0; bln6s11l=0; bln6s11p=0; th1s4l=0; th1s4p=0;
                    th5s9l=0; th5s9p=0; th10s14l=0; th10s14p=0; th15s19l=0; th15s19p=0;
                    th20s24l=0; th20s24p=0; th25s29l=0; th25s29p=0; th30s34l=0; th30s34p=0;
                    th35s39l=0; th35s39p=0; th40s44l=0; th40s44p=0; th45s49l=0; th45s49p=0;
                    th50s54l=0; th50s54p=0; th55s59l=0; th55s59p=0; th60s64l=0; th60s64p=0;
                    th65s69l=0; th65s69p=0; th70s74l=0; th70s74p=0; th75s79l=0; th75s79p=0;
                    th80s84l=0; th80s84p=0; lbth85l=0; lbth85p=0; mati=0;

                    // Query Pasien per Diagnosa (Sama seperti DlgRL4ASebab)
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            // Logika Pengelompokan Usia BARU (Sama seperti DlgRL4ASebab)
                            String jk = rs2.getString("jk");
                            String sttsumur = rs2.getString("sttsumur");
                            int umurdaftar = rs2.getInt("umurdaftar");

                            if (sttsumur.equals("Hr")) {
                                if (umurdaftar >= 1 && umurdaftar <= 7) {
                                    if (jk.equals("L")) hr1s7l++; else hr1s7p++;
                                } else if (umurdaftar >= 8 && umurdaftar <= 28) {
                                    if (jk.equals("L")) hr8s28l++; else hr8s28p++;
                                } else if (umurdaftar >= 29) {
                                    if (jk.equals("L")) hr29k3blnl++; else hr29k3blnp++;
                                }
                            } else if (sttsumur.equals("Bl")) {
                                if (umurdaftar < 3) {
                                    if (jk.equals("L")) hr29k3blnl++; else hr29k3blnp++;
                                } else if (umurdaftar >= 3 && umurdaftar <= 5) {
                                    if (jk.equals("L")) bln3s5l++; else bln3s5p++;
                                } else if (umurdaftar >= 6 && umurdaftar <= 11) {
                                    if (jk.equals("L")) bln6s11l++; else bln6s11p++;
                                }
                            } else if (sttsumur.equals("Th")) {
                                if (umurdaftar >= 1 && umurdaftar <= 4) {
                                    if (jk.equals("L")) th1s4l++; else th1s4p++;
                                } else if (umurdaftar >= 5 && umurdaftar <= 9) {
                                    if (jk.equals("L")) th5s9l++; else th5s9p++;
                                } else if (umurdaftar >= 10 && umurdaftar <= 14) {
                                    if (jk.equals("L")) th10s14l++; else th10s14p++;
                                } else if (umurdaftar >= 15 && umurdaftar <= 19) {
                                    if (jk.equals("L")) th15s19l++; else th15s19p++;
                                } else if (umurdaftar >= 20 && umurdaftar <= 24) {
                                    if (jk.equals("L")) th20s24l++; else th20s24p++;
                                } else if (umurdaftar >= 25 && umurdaftar <= 29) {
                                    if (jk.equals("L")) th25s29l++; else th25s29p++;
                                } else if (umurdaftar >= 30 && umurdaftar <= 34) {
                                    if (jk.equals("L")) th30s34l++; else th30s34p++;
                                } else if (umurdaftar >= 35 && umurdaftar <= 39) {
                                    if (jk.equals("L")) th35s39l++; else th35s39p++;
                                } else if (umurdaftar >= 40 && umurdaftar <= 44) {
                                    if (jk.equals("L")) th40s44l++; else th40s44p++;
                                } else if (umurdaftar >= 45 && umurdaftar <= 49) {
                                    if (jk.equals("L")) th45s49l++; else th45s49p++;
                                } else if (umurdaftar >= 50 && umurdaftar <= 54) {
                                    if (jk.equals("L")) th50s54l++; else th50s54p++;
                                } else if (umurdaftar >= 55 && umurdaftar <= 59) {
                                    if (jk.equals("L")) th55s59l++; else th55s59p++;
                                } else if (umurdaftar >= 60 && umurdaftar <= 64) {
                                    if (jk.equals("L")) th60s64l++; else th60s64p++;
                                } else if (umurdaftar >= 65 && umurdaftar <= 69) {
                                    if (jk.equals("L")) th65s69l++; else th65s69p++;
                                } else if (umurdaftar >= 70 && umurdaftar <= 74) {
                                    if (jk.equals("L")) th70s74l++; else th70s74p++;
                                } else if (umurdaftar >= 75 && umurdaftar <= 79) {
                                    if (jk.equals("L")) th75s79l++; else th75s79p++;
                                } else if (umurdaftar >= 80 && umurdaftar <= 84) {
                                    if (jk.equals("L")) th80s84l++; else th80s84p++;
                                } else if (umurdaftar >= 85) {
                                    if (jk.equals("L")) lbth85l++; else lbth85p++;
                                }
                            }
                        } // End While rs2
                    } catch (Exception e) {
                        System.out.println("Notifikasi ps2: "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    } // End Try Catch Finally ps2

                    // Query Pasien Mati (Sama seperti DlgRL4ASebab)
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=? ");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        if(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("Notifikasi ps3: "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps3!=null){
                            ps3.close();
                        }
                    } // End Try Catch Finally ps3

                    // Membuat Baris Data HTML Baru (Sama seperti DlgRL4ASebab)
                    htmlContent.append("<tr class='isi'>");
                    htmlContent.append("<td valign='middle' align='center'>").append(i).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(rs.getString("kd_penyakit")).append("</td>");
                    htmlContent.append("<td valign='middle' align='left'>").append(rs.getString("nm_penyakit")).append("</td>");
                    // Data Kolom Usia Baru (L/P)
                    htmlContent.append("<td valign='middle' align='center'>").append(hr1s7l).append("</td><td valign='middle' align='center'>").append(hr1s7p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(hr8s28l).append("</td><td valign='middle' align='center'>").append(hr8s28p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(hr29k3blnl).append("</td><td valign='middle' align='center'>").append(hr29k3blnp).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(bln3s5l).append("</td><td valign='middle' align='center'>").append(bln3s5p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(bln6s11l).append("</td><td valign='middle' align='center'>").append(bln6s11p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th1s4l).append("</td><td valign='middle' align='center'>").append(th1s4p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th5s9l).append("</td><td valign='middle' align='center'>").append(th5s9p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th10s14l).append("</td><td valign='middle' align='center'>").append(th10s14p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th15s19l).append("</td><td valign='middle' align='center'>").append(th15s19p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th20s24l).append("</td><td valign='middle' align='center'>").append(th20s24p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th25s29l).append("</td><td valign='middle' align='center'>").append(th25s29p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th30s34l).append("</td><td valign='middle' align='center'>").append(th30s34p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th35s39l).append("</td><td valign='middle' align='center'>").append(th35s39p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th40s44l).append("</td><td valign='middle' align='center'>").append(th40s44p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th45s49l).append("</td><td valign='middle' align='center'>").append(th45s49p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th50s54l).append("</td><td valign='middle' align='center'>").append(th50s54p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th55s59l).append("</td><td valign='middle' align='center'>").append(th55s59p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th60s64l).append("</td><td valign='middle' align='center'>").append(th60s64p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th65s69l).append("</td><td valign='middle' align='center'>").append(th65s69p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th70s74l).append("</td><td valign='middle' align='center'>").append(th70s74p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th75s79l).append("</td><td valign='middle' align='center'>").append(th75s79p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th80s84l).append("</td><td valign='middle' align='center'>").append(th80s84p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(lbth85l).append("</td><td valign='middle' align='center'>").append(lbth85p).append("</td>");

                    // Hitung Total Laki-laki (LK)
                    int totalL = hr1s7l + hr8s28l + hr29k3blnl + bln3s5l + bln6s11l + th1s4l + th5s9l + th10s14l +
                                 th15s19l + th20s24l + th25s29l + th30s34l + th35s39l + th40s44l + th45s49l + th50s54l +
                                 th55s59l + th60s64l + th65s69l + th70s74l + th75s79l + th80s84l + lbth85l;
                    // Hitung Total Perempuan (PR)
                    int totalP = hr1s7p + hr8s28p + hr29k3blnp + bln3s5p + bln6s11p + th1s4p + th5s9p + th10s14p +
                                 th15s19p + th20s24p + th25s29p + th30s34p + th35s39p + th40s44p + th45s49p + th50s54p +
                                 th55s59p + th60s64p + th65s69p + th70s74p + th75s79p + th80s84p + lbth85p;

                    htmlContent.append("<td valign='middle' align='center'>").append(totalL).append("</td>"); // Total LK
                    htmlContent.append("<td valign='middle' align='center'>").append(totalP).append("</td>"); // Total PR
                    htmlContent.append("<td valign='middle' align='center'>").append(totalL + totalP - mati).append("</td>"); // Jumlah Hidup
                    htmlContent.append("<td valign='middle' align='center'>").append(mati).append("</td>"); // Jumlah Mati
                    htmlContent.append("</tr>");
                    i++;
                } // End While rs
            } catch (Exception e) {
                System.out.println("Notifikasi ps: "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            } // End Try Catch Finally ps

            // Menampilkan Hasil ke LoadHTML
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("Notifikasi prosesCari: "+e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }

    // ==================================================================================================================
    // == METODE prosesCari2() DIMODIFIKASI ==
    // ==================================================================================================================
    private void prosesCari2() {
       this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();

            // Membuat Header Tabel HTML Baru (Sama seperti prosesCari)
            htmlContent.append(
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='3'>No.Urut</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='4%' rowspan='3'>No.Daftar Terperinci</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='15%' rowspan='3'>Golongan Sebab Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='46'>Jumlah Pasien Hidup dan Mati menurut Golongan Umur & Jenis Kelamin</td>"+ // 23 kelompok * 2 gender = 46 kolom
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='6%' colspan='2'>Pasien Keluar (Hidup & Mati) Menurut Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='3%' rowspan='3'>Jumlah Pasien Keluar Hidup (Î£ Kolom L + Î£ Kolom P)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='3%' rowspan='3'>Jumlah Pasien Keluar Mati</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    // Rentang usia baru (tanpa jam)
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-7 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>8-28 hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>29hr-<3 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>3-5 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>6-11 bln</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-4 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>5-9 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>10-14 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>15-19 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>20-24 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>25-29 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>30-34 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>35-39 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>40-44 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>45-49 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>50-54 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>55-59 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>60-64 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>65-69 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>70-74 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>75-79 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>80-84 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>â‰¥ 85 th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>LK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>PR</td>"+
                "</tr>"+
                 "<tr class='isi'>");
            // Loop untuk L/P di setiap kolom umur
            for(int k=0; k<23; k++){ // 23 kelompok umur baru (tanpa jam)
                htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td><td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>");
            }
            htmlContent.append("</tr>");

            // Baris nomor kolom (Sama seperti prosesCari)
            htmlContent.append("<tr class='isi'>");
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"); // No Urut
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"); // No Daftar
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"); // Golongan Sebab
            int colNum = 4;
            for(int k=0; k< (23 * 2); k++){ // Kolom 4 sampai 49 untuk L/P
                 htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>");
            }
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Total LK (Kolom 50)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Total PR (Kolom 51)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum++).append("</td>"); // Jumlah Hidup (Kolom 52)
            htmlContent.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>").append(colNum).append("</td>");   // Jumlah Mati (Kolom 53)
            htmlContent.append("</tr>");

            // Query Utama (Dipertahankan dari DlgRL4A.java ASLI - Berdasarkan Tanggal Keluar & Exclude V,W,X,Y)
            // Menggunakan AND untuk exclude V,W,X,Y
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa inner join kamar_inap on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' and diagnosa_pasien.prioritas='1' and "+
                    " kamar_inap.tgl_keluar between ? and ? and "+
                    " left(diagnosa_pasien.kd_penyakit,1)<>'V' and left(diagnosa_pasien.kd_penyakit,1)<>'W' and "+ // Menggunakan AND
                    " left(diagnosa_pasien.kd_penyakit,1)<>'X' and left(diagnosa_pasien.kd_penyakit,1)<>'Y' "+
                    " group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1; // Reset nomor urut
                while(rs.next()){
                    // Reset semua counter baru (Sama seperti prosesCari)
                    hr1s7l=0; hr1s7p=0; hr8s28l=0; hr8s28p=0; hr29k3blnl=0; hr29k3blnp=0;
                    bln3s5l=0; bln3s5p=0; bln6s11l=0; bln6s11p=0; th1s4l=0; th1s4p=0;
                    th5s9l=0; th5s9p=0; th10s14l=0; th10s14p=0; th15s19l=0; th15s19p=0;
                    th20s24l=0; th20s24p=0; th25s29l=0; th25s29p=0; th30s34l=0; th30s34p=0;
                    th35s39l=0; th35s39p=0; th40s44l=0; th40s44p=0; th45s49l=0; th45s49p=0;
                    th50s54l=0; th50s54p=0; th55s59l=0; th55s59p=0; th60s64l=0; th60s64p=0;
                    th65s69l=0; th65s69p=0; th70s74l=0; th70s74p=0; th75s79l=0; th75s79p=0;
                    th80s84l=0; th80s84p=0; lbth85l=0; lbth85p=0; mati=0;

                    // Query Pasien per Diagnosa (Dipertahankan dari DlgRL4A.java ASLI - Berdasarkan Tanggal Keluar)
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' "+ // Mungkin perlu tambah prioritas='1'
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            // Logika Pengelompokan Usia BARU (Sama seperti prosesCari)
                             String jk = rs2.getString("jk");
                            String sttsumur = rs2.getString("sttsumur");
                            int umurdaftar = rs2.getInt("umurdaftar");

                            if (sttsumur.equals("Hr")) {
                                if (umurdaftar >= 1 && umurdaftar <= 7) {
                                    if (jk.equals("L")) hr1s7l++; else hr1s7p++;
                                } else if (umurdaftar >= 8 && umurdaftar <= 28) {
                                    if (jk.equals("L")) hr8s28l++; else hr8s28p++;
                                } else if (umurdaftar >= 29) {
                                    if (jk.equals("L")) hr29k3blnl++; else hr29k3blnp++;
                                }
                            } else if (sttsumur.equals("Bl")) {
                                if (umurdaftar < 3) {
                                    if (jk.equals("L")) hr29k3blnl++; else hr29k3blnp++;
                                } else if (umurdaftar >= 3 && umurdaftar <= 5) {
                                    if (jk.equals("L")) bln3s5l++; else bln3s5p++;
                                } else if (umurdaftar >= 6 && umurdaftar <= 11) {
                                    if (jk.equals("L")) bln6s11l++; else bln6s11p++;
                                }
                            } else if (sttsumur.equals("Th")) {
                                if (umurdaftar >= 1 && umurdaftar <= 4) {
                                    if (jk.equals("L")) th1s4l++; else th1s4p++;
                                } else if (umurdaftar >= 5 && umurdaftar <= 9) {
                                    if (jk.equals("L")) th5s9l++; else th5s9p++;
                                } else if (umurdaftar >= 10 && umurdaftar <= 14) {
                                    if (jk.equals("L")) th10s14l++; else th10s14p++;
                                } else if (umurdaftar >= 15 && umurdaftar <= 19) {
                                    if (jk.equals("L")) th15s19l++; else th15s19p++;
                                } else if (umurdaftar >= 20 && umurdaftar <= 24) {
                                    if (jk.equals("L")) th20s24l++; else th20s24p++;
                                } else if (umurdaftar >= 25 && umurdaftar <= 29) {
                                    if (jk.equals("L")) th25s29l++; else th25s29p++;
                                } else if (umurdaftar >= 30 && umurdaftar <= 34) {
                                    if (jk.equals("L")) th30s34l++; else th30s34p++;
                                } else if (umurdaftar >= 35 && umurdaftar <= 39) {
                                    if (jk.equals("L")) th35s39l++; else th35s39p++;
                                } else if (umurdaftar >= 40 && umurdaftar <= 44) {
                                    if (jk.equals("L")) th40s44l++; else th40s44p++;
                                } else if (umurdaftar >= 45 && umurdaftar <= 49) {
                                    if (jk.equals("L")) th45s49l++; else th45s49p++;
                                } else if (umurdaftar >= 50 && umurdaftar <= 54) {
                                    if (jk.equals("L")) th50s54l++; else th50s54p++;
                                } else if (umurdaftar >= 55 && umurdaftar <= 59) {
                                    if (jk.equals("L")) th55s59l++; else th55s59p++;
                                } else if (umurdaftar >= 60 && umurdaftar <= 64) {
                                    if (jk.equals("L")) th60s64l++; else th60s64p++;
                                } else if (umurdaftar >= 65 && umurdaftar <= 69) {
                                    if (jk.equals("L")) th65s69l++; else th65s69p++;
                                } else if (umurdaftar >= 70 && umurdaftar <= 74) {
                                    if (jk.equals("L")) th70s74l++; else th70s74p++;
                                } else if (umurdaftar >= 75 && umurdaftar <= 79) {
                                    if (jk.equals("L")) th75s79l++; else th75s79p++;
                                } else if (umurdaftar >= 80 && umurdaftar <= 84) {
                                    if (jk.equals("L")) th80s84l++; else th80s84p++;
                                } else if (umurdaftar >= 85) {
                                    if (jk.equals("L")) lbth85l++; else lbth85p++;
                                }
                            }
                        } // End While rs2
                    } catch (Exception e) {
                        System.out.println("Notifikasi ps2: "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    } // End Try Catch Finally ps2

                    // Query Pasien Mati (Dipertahankan dari DlgRL4A.java ASLI - Berdasarkan Tanggal Keluar)
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' and kamar_inap.no_rawat=reg_periksa.no_rawat "+ // Join kamar_inap
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=? "); // Filter tgl_keluar
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        if(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("Notifikasi ps3: "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps3!=null){ // Pastikan ps3 ditutup
                            ps3.close();
                        }
                    } // End Try Catch Finally ps3


                    // Membuat Baris Data HTML Baru (Sama seperti prosesCari)
                    htmlContent.append("<tr class='isi'>");
                    htmlContent.append("<td valign='middle' align='center'>").append(i).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(rs.getString("kd_penyakit")).append("</td>");
                    htmlContent.append("<td valign='middle' align='left'>").append(rs.getString("nm_penyakit")).append("</td>");
                    // Data Kolom Usia Baru (L/P)
                    htmlContent.append("<td valign='middle' align='center'>").append(hr1s7l).append("</td><td valign='middle' align='center'>").append(hr1s7p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(hr8s28l).append("</td><td valign='middle' align='center'>").append(hr8s28p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(hr29k3blnl).append("</td><td valign='middle' align='center'>").append(hr29k3blnp).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(bln3s5l).append("</td><td valign='middle' align='center'>").append(bln3s5p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(bln6s11l).append("</td><td valign='middle' align='center'>").append(bln6s11p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th1s4l).append("</td><td valign='middle' align='center'>").append(th1s4p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th5s9l).append("</td><td valign='middle' align='center'>").append(th5s9p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th10s14l).append("</td><td valign='middle' align='center'>").append(th10s14p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th15s19l).append("</td><td valign='middle' align='center'>").append(th15s19p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th20s24l).append("</td><td valign='middle' align='center'>").append(th20s24p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th25s29l).append("</td><td valign='middle' align='center'>").append(th25s29p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th30s34l).append("</td><td valign='middle' align='center'>").append(th30s34p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th35s39l).append("</td><td valign='middle' align='center'>").append(th35s39p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th40s44l).append("</td><td valign='middle' align='center'>").append(th40s44p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th45s49l).append("</td><td valign='middle' align='center'>").append(th45s49p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th50s54l).append("</td><td valign='middle' align='center'>").append(th50s54p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th55s59l).append("</td><td valign='middle' align='center'>").append(th55s59p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th60s64l).append("</td><td valign='middle' align='center'>").append(th60s64p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th65s69l).append("</td><td valign='middle' align='center'>").append(th65s69p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th70s74l).append("</td><td valign='middle' align='center'>").append(th70s74p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th75s79l).append("</td><td valign='middle' align='center'>").append(th75s79p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(th80s84l).append("</td><td valign='middle' align='center'>").append(th80s84p).append("</td>");
                    htmlContent.append("<td valign='middle' align='center'>").append(lbth85l).append("</td><td valign='middle' align='center'>").append(lbth85p).append("</td>");

                    // Hitung Total Laki-laki (LK)
                    int totalL = hr1s7l + hr8s28l + hr29k3blnl + bln3s5l + bln6s11l + th1s4l + th5s9l + th10s14l +
                                 th15s19l + th20s24l + th25s29l + th30s34l + th35s39l + th40s44l + th45s49l + th50s54l +
                                 th55s59l + th60s64l + th65s69l + th70s74l + th75s79l + th80s84l + lbth85l;
                    // Hitung Total Perempuan (PR)
                    int totalP = hr1s7p + hr8s28p + hr29k3blnp + bln3s5p + bln6s11p + th1s4p + th5s9p + th10s14p +
                                 th15s19p + th20s24p + th25s29p + th30s34p + th35s39p + th40s44p + th45s49p + th50s54p +
                                 th55s59p + th60s64p + th65s69p + th70s74p + th75s79p + th80s84p + lbth85p;

                    htmlContent.append("<td valign='middle' align='center'>").append(totalL).append("</td>"); // Total LK
                    htmlContent.append("<td valign='middle' align='center'>").append(totalP).append("</td>"); // Total PR
                    htmlContent.append("<td valign='middle' align='center'>").append(totalL + totalP - mati).append("</td>"); // Jumlah Hidup
                    htmlContent.append("<td valign='middle' align='center'>").append(mati).append("</td>"); // Jumlah Mati
                    htmlContent.append("</tr>");

                    i++;
                } // End While rs
            } catch (Exception e) {
                 System.out.println("Notifikasi ps: "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            } // End Try Catch Finally ps

            // Menampilkan Hasil ke LoadHTML1
            LoadHTML1.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
             System.out.println("Notifikasi prosesCari2: "+e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }
    
    
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getrl4asebab());
    }
    
}
